name: Automated CI tests

on:
  push:
  workflow_dispatch:
    inputs:
      deployment-target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
            - regression
            - regress_extended

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '18'

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - name: regression
        run: mvn test -Dbrowser=chrome -Dsurefire.suiteXmlFiles=src/test/resources/testng.xml -Dgroups=Regression
        if: "github.event.inputs.deployment-target == 'regression'"
      - name: regress+extended
        run: mvn test -Dbrowser=chrome -Dsurefire.suiteXmlFiles=src/test/resources/testng.xml
        if: "github.event.inputs.deployment-target == 'regress_extended'"
